name: CI-SFTP
 
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ main ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "SFTP"
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build
          
      - name: Clean Remote Directory
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ssh.strato.de
          username: 570421463.swh.strato-hosting.eu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Option 1: Lösche alle Dateien im Zielordner
            # rm -rf /var/www/*
            # Option 2: Alternativ: Verschiebe alte Dateien in einen Backup-Ordner
            mv /webseite/ /webseite_backup

 # Deploy only the dist folder via SFTP
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: 570421463.swh.strato-hosting.eu
          server: ssh.strato.de
          port: 22 # default is 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: ./dist/* # Deploy only the contents of the dist folder
          remote_path: /webseite
          args: '-o ConnectTimeout=5'
    
